### ISSUE TITLE
I could not find 'scnet' package that you mentioned in reproducibility.

### ISSUE THREAD

**Issue by HaHaLiang666** [theislab/scArches-reproducibility#8]
I want to transfer annotations from reference to query.

**Comment by M0hammadL** [comment]
https://scarches.readthedocs.io/en/latest/scanvi_surgery_pipeline.html see here

**Comment by HaHaLiang666** [comment]
Thanks for your reply!
I have a new cell-type label in my query data.
However, in your tips about scANVI (https://scarches.readthedocs.io/en/latest/training_tips.html): If you have a new cell-type label that is in the query data but not in reference and you want to use this in the training query you will get an error! We will fix this in future releases.

**Comment by M0hammadL** [comment]
Ahh that is not supported now, stay tuned we will have an update sooon
